[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/nl/*"
  to = "/de/404.html"
  status = 404