// Generated by Wrangler by running `wrangler types --env dev`

interface Env {
	TERRADELFT_WEBSITE: KVNamespace;
	ALGOLIA_API_KEY: string;
	ALGOLIA_APP_ID: string;
	CONTENTFUL_KEY: string;
	CONTENTFUL_SPACE: string;
	EMAIL_RECEIVER: string;
	EMAIL_BCC: string;
	SENDINBLUE_KEY: string;
	SENTRY_AUTH_TOKEN: string;
	SENTRY_ORG: string;
	SENTRY_PROJECT: string;
	STRIPE_KEY_PRIVATE: string;
	STRIPE_KEY_PUBLIC: string;
	TERRADELFT_GRAPHQL: AnalyticsEngineDataset;
}
