name = "worker-typescript-template"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = false

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"