name = "terradelft-api-development"
type = "javascript"
zone_id = "378eda59b41c3b17e112ca517f7eaf62"
account_id = "4b99fe044748e20b67286e12a4f239fb"
route = "testapi.terra-delft.nl/*"
workers_dev = true

[build]
command = "yarn && yarn build"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.production]
name = "terradelft-api"
route = "api.terra-delft.nl/*"