name: Preview deployment

on:
  push:
    branches:
      - preview
  repository_dispatch:
    types: [preview]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
      - name: -- Step 2 -- Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: -- Step 3 -- Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./gatsby/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./gatsby/package-lock.json') }}
          # restore-keys: |
          #   ${{ runner.os }}-node-modules-
      # - name: -- Step 4 -- Cache Gatsby
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ./gatsby/.cache
      #       ./gatsby/public
      #     key: ${{ runner.os }}-gatsby-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-gatsby-
      - name: -- Step 5 -- Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./gatsby
        run: npm install
      - name: -- Step 6 -- Build static site
        timeout-minutes: 30
        working-directory: ./gatsby
        run: npm run build
        env:
          CI: true
          CONTENTFUL_HOST: cdn.contentful.com
          CONTENTFUL_OBJECTS_SPACE: ${{ secrets.CONTENTFUL_OBJECTS_SPACE }}
          CONTENTFUL_OBJECTS_ENVIRONMENT: master
          CONTENTFUL_OBJECTS_KEY_GATSBY: ${{ secrets.CONTENTFUL_OBJECTS_KEY_GATSBY_PREVIEW }}
          CONTENTFUL_OBJECTS_KEY_CHECKOUT: ${{ secrets.CONTENTFUL_OBJECTS_KEY_CHECKOUT_PREVIEW }}
          CONTENTFUL_CONTENTS_SPACE: ${{ secrets.CONTENTFUL_CONTENTS_SPACE }}
          CONTENTFUL_CONTENTS_ENVIRONMENT: master
          CONTENTFUL_CONTENTS_KEY: ${{ secrets.CONTENTFUL_CONTENTS_KEY_PREVIEW }}
          GATSBY_RECAPTCHA_PUBLIC_KEY: ${{ secrets.GATSBY_RECAPTCHA_PUBLIC_KEY_PREVIEW }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY_PREVIEW }}
          GATSBY_STRIPE_PUBLIC_KEY: ${{ secrets.GATSBY_STRIPE_PUBLIC_KEY_PREVIEW }}
          STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY_PREVIEW }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          GATSBY_API_ENDPOINT: preview.api.terra-delft.nl
      - name: -- Step 7 -- Deploy to one.com
        uses: xmflsct/sftp-upload-action@v0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          localDir: './gatsby'
          remoteDir: '/www/preview/'
          dryRun: true
          exclude: '[".well-known", ".htaccess", "htpasswd"]'
      # - name: -- Step 7 -- Deploy to one.com
      #   working-directory: ./gatsby
      #   env:
      #     remote_host: ${{ secrets.DEPLOY_HOST }}
      #     remote_port: ${{ secrets.DEPLOY_PORT }}
      #     remote_user: ${{ secrets.DEPLOY_USER }}
      #     remote_pass: ${{ secrets.DEPLOY_PASS }}
      #     local_dir: 'public/'
      #     remote_dir: '/www/preview/'
      #   run: |
      #     sh ./scripts/rsync-preview.sh
      - name: -- Step 8 -- Email notification
        if: github.event_name == 'repository_dispatch'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: send.one.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Preview deployment succeed
          body: The website is live at https://preview.terra-delft.nl
          to: shop@terra-delft.nl,xmflsct@gmail.com
          from: no-reply@terra-delft.nl
