name: Production deployment

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
      - name: -- Step 2 -- Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: -- Step 3 -- Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: './gatsby/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./gatsby/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: -- Step 4 -- Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./gatsby
        run: yarn
      - name: -- Step 5 -- Build static site
        timeout-minutes: 30
        working-directory: ./gatsby
        run: yarn build
        env:
          CI: true
          CONTENTFUL_HOST: cdn.contentful.com
          CONTENTFUL_OBJECTS_SPACE: ${{ secrets.CONTENTFUL_OBJECTS_SPACE }}
          CONTENTFUL_OBJECTS_ENVIRONMENT: master
          CONTENTFUL_OBJECTS_KEY_GATSBY: ${{ secrets.CONTENTFUL_OBJECTS_KEY_GATSBY_PRODUCTION }}
          CONTENTFUL_OBJECTS_KEY_CHECKOUT: ${{ secrets.CONTENTFUL_OBJECTS_KEY_CHECKOUT_PRODUCTION }}
          CONTENTFUL_CONTENTS_SPACE: ${{ secrets.CONTENTFUL_CONTENTS_SPACE }}
          CONTENTFUL_CONTENTS_ENVIRONMENT: master
          CONTENTFUL_CONTENTS_KEY: ${{ secrets.CONTENTFUL_CONTENTS_KEY_PRODUCTION }}
          GATSBY_RECAPTCHA_PUBLIC_KEY: ${{ secrets.GATSBY_RECAPTCHA_PUBLIC_KEY_PRODUCTION }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY_PRODUCTION }}
          GATSBY_STRIPE_PUBLIC_KEY: ${{ secrets.GATSBY_STRIPE_PUBLIC_KEY_PRODUCTION }}
          STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY_PRODUCTION }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          GATSBY_API_ENDPOINT: api.terra-delft.nl
      - name: -- Step 6 -- Deploy to one.com
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          log-level: minimal
          local-dir: './gatsby/public/'
          server-dir: '/'
          exclude: .htaccess
            - archive1
            - archive2
            - preview
      - name: -- Step 7 -- Email notification
        if: github.event_name == 'repository_dispatch'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: send.one.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Production deployment succeed
          body: The website is live at https://terra-delft.nl
          to: shop@terra-delft.nl,xmflsct@gmail.com
          from: no-reply@terra-delft.nl
