name: Production deployment

on:
  repository_dispatch:
    types: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
      - name: -- Step 2 -- Update current time
        run: date +"%s" > ./VERSION
      - name: -- Step 3 -- Commit versioning
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com